CREATE TABLE [dbo].[Clients]
(
	[ClientId] INT IDENTITY NOT NULL PRIMARY KEY,
	[LastName] NVARCHAR(30) NOT NULL,
	[FirstName] NVARCHAR(30) NOT NULL,
	[PhoneNumber] NVARCHAR(20) NOT NULL,
	[Email] NVARCHAR(40) NOT NULL
)
